### ISSUE TITLE
Support for additional custom field types?

### ISSUE THREAD

**Issue by scriptninja** [ljader/redmine-mylyn-plugin#23]
I have the Andriy Lesyuk's extended fields plugin installed: http://projects.andriylesyuk.com/projects/extended-fields

(...I wonder how to pronounce his name...)

Anyhow, when trying to synchronize issues, getTaskAttributeType fails when trying to cope with the added custom field types. I would assume that similar plugins would suffer a similar problem. (Stack trace from my log file included at the bottom.)

I think for the time being I am going to switch to Anton Argirov's Textilizable Custom Fields plugin, which for my current purposes should serve just as well, and which I suspect does not add more custom field types but merely adds functionality to existing ones. However, I thought you might want to take a look at whether it is possible to add a fallback so that plugin-contributed custom field types don't cause this problem. I doubt it would be practical to support editing such fields, but ignoring them instead of throwing an exception seems feasible.

!ENTRY org.eclipse.mylyn.tasks.core 4 0 2013-08-02 08:35:33.286
!MESSAGE Synchronization failed
!STACK 0
java.lang.NullPointerException
    at net.sf.redmine_mylyn.core.RedmineUtil.getTaskAttributeType(RedmineUtil.java:79)
    at net.sf.redmine_mylyn.core.RedmineTaskDataHandler.createAttribute(RedmineTaskDataHandler.java:366)
    at net.sf.redmine_mylyn.core.RedmineTaskDataHandler.createCustomAttributes(RedmineTaskDataHandler.java:331)
    at net.sf.redmine_mylyn.core.RedmineTaskDataHandler.createAttributes(RedmineTaskDataHandler.java:190)
    at net.sf.redmine_mylyn.core.RedmineTaskDataHandler.createTaskDataFromIssue(RedmineTaskDataHandler.java:177)
    at net.sf.redmine_mylyn.core.RedmineRepositoryConnector.performQuery(RedmineRepositoryConnector.java:252)
    at org.eclipse.mylyn.internal.tasks.core.sync.SynchronizeQueriesJob.synchronizeQuery(SynchronizeQueriesJob.java:311)
    at org.eclipse.mylyn.internal.tasks.core.sync.SynchronizeQueriesJob.synchronizeQueries(SynchronizeQueriesJob.java:268)
    at org.eclipse.mylyn.internal.tasks.core.sync.SynchronizeQueriesJob.run(SynchronizeQueriesJob.java:201)
    at org.eclipse.core.internal.jobs.Worker.run(Worker.java:53)

**Comment by DzianisFrydliand** [comment]
We've ran into the same issue. The reason was a custom field with type "URL", which we added to our redmine configuration.
Could you please suggest any walkaround?

**Comment by ljader** [comment]
Hi all.
The issue with custom field "link" (both Andriy Lesyuk's plugin and Redmine core 2.5) has been fixed in new 0.5.1 version of the plugin - please check https://github.com/ljader/redmine-mylyn-plugin/releases

The support for other custom fields is not planned at the moment.

Thank you all for your help.
