### ISSUE TITLE
Syncronization fails creating query

### ISSUE THREAD

**Issue by candaya** [ljader/redmine-mylyn-plugin#52]
I am getting a sync failure when I create queries.
Stack trace:
java.lang.NullPointerException
    at net.sf.redmine_mylyn.core.RedmineUtil.getTaskAttributeType(RedmineUtil.java:79)
    at net.sf.redmine_mylyn.core.RedmineTaskDataHandler.createAttribute(RedmineTaskDataHandler.java:369)
    at net.sf.redmine_mylyn.core.RedmineTaskDataHandler.createCustomAttributes(RedmineTaskDataHandler.java:334)
    at net.sf.redmine_mylyn.core.RedmineTaskDataHandler.createAttributes(RedmineTaskDataHandler.java:193)
    at net.sf.redmine_mylyn.core.RedmineTaskDataHandler.createTaskDataFromIssue(RedmineTaskDataHandler.java:180)
    at net.sf.redmine_mylyn.core.RedmineRepositoryConnector.performQuery(RedmineRepositoryConnector.java:252)
    at org.eclipse.mylyn.internal.tasks.core.sync.SynchronizeQueriesJob.synchronizeQuery(SynchronizeQueriesJob.java:312)
    at org.eclipse.mylyn.internal.tasks.core.sync.SynchronizeQueriesJob.synchronizeQueries(SynchronizeQueriesJob.java:269)
    at org.eclipse.mylyn.internal.tasks.core.sync.SynchronizeQueriesJob.run(SynchronizeQueriesJob.java:201)
    at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)

Session Data:
eclipse.buildId=M20130131-0800
java.version=1.7.0_40
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86, WS=win32, NL=en_US
Command-line arguments:  -os win32 -ws win32 -arch x86

**Comment by awilkins** [comment]
This looks very like the issue in #23 ; are you using custom field types?

**Comment by mpieck** [comment]
Is there anything going on to resolve this issue? I use custom fields in my Redmine installation and have the same NPE:

java.lang.NullPointerException
	at net.sf.redmine_mylyn.core.RedmineUtil.getTaskAttributeType(RedmineUtil.java:79)

which causes, that the plugin is completely useless.

**Comment by ljader** [comment]
@mpieck Could you give more detais about your system?

    Redmine version
    Eclipse version
    Redmine Mylyn Eclipse Plugin version
    Redmine Mylyn Connector version and url where you get it
    are you connecting using API Key or User/Pass

**Comment by mpieck** [comment]
@ljader 

Redmine v2.5.1
Eclipse v. 4.5.2.M20160212-1500
Redmine Mylyn Eclipse Plugin 0.4.0.201602071631
Redmine Mylyn Connector 2.8.2, don't know the plugin source url, because I didn't install it.

I am connecting with API Key because User/Pass does not work for me in Mylyn (I get authentication failed, although I can log in with it via Redmine web UI).

**Comment by ljader** [comment]
Hi all.
The issue with custom fields has been fixed in new 0.5.1 version of the plugin, so this should work as well - please check https://github.com/ljader/redmine-mylyn-plugin/releases

Thank you all for your help.
