### ISSUE TITLE
Installed latest version successfully on Marse (4.5.2), but doesn't work!

### ISSUE THREAD

**Issue by hedayat** [ljader/redmine-mylyn-plugin#73]
Is there any logs I can inspect?!

**Comment by hedayat** [comment]
Found:
`org.osgi.framework.BundleException: Could not resolve module: net.sf.redmine_mylyn.api [23]
  Unresolved requirement: Require-Bundle: net.sf.redmine_mylyn.common; bundle-version="0.4.0"
    -> Bundle-SymbolicName: net.sf.redmine_mylyn.common; bundle-version="-1.4.0.201602071631"; singleton:="true"
       net.sf.redmine_mylyn.common [24]
         No resolution report for the bundle.  Bundle was not resolved because of a uses contraint violation.
  org.osgi.service.resolver.ResolutionException: Uses constraint violation. Unable to resolve resource net.sf.redmine_mylyn.common [osgi.identity; osgi.identity="net.sf.redmine_mylyn.common"; type="osgi.bundle"; version:Version="0.4.0.201602071631"; singleton:="true"] because it is exposed to package 'org.slf4j.helpers' from resources org.slf4j.api [osgi.identity; osgi.identity="org.slf4j.api"; type="osgi.bundle"; version:Version="1.7.2.v20121108-1250"] and slf4j.api [osgi.identity; osgi.identity="slf4j.api"; type="osgi.bundle"; version:Version="1.7.12"] via two dependency chains.

Chain 1:
  net.sf.redmine_mylyn.common [osgi.identity; osgi.identity="net.sf.redmine_mylyn.common"; type="osgi.bundle"; version:Version="0.4.0.201602071631"; singleton:="true"]
    require: (&(osgi.wiring.bundle=org.slf4j.api)(bundle-version>=1.5.11))
     |
    provide: osgi.wiring.bundle: org.slf4j.api
  org.slf4j.api [osgi.identity; osgi.identity="org.slf4j.api"; type="osgi.bundle"; version:Version="1.7.2.v20121108-1250"]

Chain 2:
  net.sf.redmine_mylyn.common [osgi.identity; osgi.identity="net.sf.redmine_mylyn.common"; type="osgi.bundle"; version:Version="0.4.0.201602071631"; singleton:="true"]
    require: (&(osgi.wiring.bundle=ch.qos.logback.classic)(bundle-version>=0.9.19))
     |
    provide: osgi.wiring.bundle; bundle-version:Version="1.0.7.v20121108-1250"; osgi.wiring.bundle="ch.qos.logback.classic"
  ch.qos.logback.classic [osgi.identity; osgi.identity="ch.qos.logback.classic"; type="osgi.bundle"; version:Version="1.0.7.v20121108-1250"]
    import: (&(osgi.wiring.package=org.slf4j.helpers)(version>=1.7.0))
     |
    export: osgi.wiring.package: org.slf4j.helpers
  slf4j.api [osgi.identity; osgi.identity="slf4j.api"; type="osgi.bundle"; version:Version="1.7.12"]
        at org.eclipse.osgi.container.Module.start(Module.java:434)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1582)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1561)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1533)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1476)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
        at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
        at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340)
`

**Comment by hedayat** [comment]
Solved somehow after fiddling with eclipse files! 
But maybe the org.slf4j.api dependency should be changed to slf4j.api in newer eclipse versions.

**Comment by ljader** [comment]
@hedayat Could you give more detais about your system?

    Redmine version
    Eclipse version (and flavor like JEE, SDK or Java...)
    Redmine Mylyn Eclipse Plugin version
    Redmine Mylyn Connector version and url where you get it
    are you connecting using API Key or User/Pass

**Comment by hedayat** [comment]
Redmine version: 3.2.x (will see the exact version number and report in a few days. No access to redmine instance right now). 
Eclipse version: 4.5.2  I'm using Fedora 23's eclipse package for C++ development. So its mainly Eclipse + CDT with a number of other plugins.
Redmine mylyn connector is the one I introduced in #72: https://github.com/joaopedrotaveira/redmine_mylyn_connector
IIRC, I'm using API key.
Eclipse plugin is the latest one available right now: https://github.com/ljader/redmine-mylyn-plugin/releases/latest

**Comment by hedayat** [comment]
Notice that it seems that the main problem is that my Eclipse installation uses slf4j.api version 1.7.12, while the plugin installs org.slf4j.api version 1.7.2.v20121108-1250, and it seems that both of these versions are 'exposed' to net.sf.redmine_mylyn.common

**Comment by ljader** [comment]
@hedayat thanks very much for the info, currently I'm working on resolving dependencies with different library but I will give this also a look.

**Comment by hedayat** [comment]
You're welcome. Thank you for considering this report & to develop this plugin. :)
Our redmine version is 3.1.1

**Comment by ljader** [comment]
Hi @hedayat  can you try to re-create the issue with recent 0.5.1 version of the plugin?
https://github.com/ljader/redmine-mylyn-plugin/releases

Thank you for your help.
